Description: Deploys the AWS CodePipeline waiter lambda into an AWS account
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Metadata:
  AWS::ServerlessRepo::Application:
    Author: Xavier Thomas
    Description: An AWS lambda that can be called from a deployment AWS CodePipeline to monitor and wait for a target CodePipeline in the same or another AWS account.
    HomePageUrl: https://github.com/xavier-thomas/aws-codepipeline-waiter
    Labels:
      - CodePipeline
      - Waiter
      - Monitoring
    LicenseUrl: LICENSE
    Name: CodePipeline-Waiter
    ReadmeUrl: README.md
    SemanticVersion: 1.2.2
    SourceCodeUrl: https://github.com/xavier-thomas/aws-codepipeline-waiter
    SpdxLicenseId: BSD-3-Clause


Resources:
  PipelineWaiterLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs12.x
      CodeUri: ./dist
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - codepipeline:ListPipelines
                - codepipeline:PutJobFailureResult
                - codepipeline:PutJobSuccessResult
              Resource: '*'
          # Allow the lambda to assume role in other accounts.
          # Replace the resource: '*' with a specific role arn if it's fixed.
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Resource: '*'


Outputs:

  PipelineWaiterLambdaArn:
    Value: !GetAtt PipelineWaiterLambda.Arn
    Export:
      Name: !Sub ${AWS::StackName}-PipelineWaiterLambdaArn

  PipelineWaiterLambdaName:
    Value: !Ref PipelineWaiterLambda
    Export:
      Name: !Sub ${AWS::StackName}-PipelineWaiterLambdaName
