Description: Deploys the pipeline monitoring lambda into an AWS account
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DevAccountId:
    Type: String
  CiAccountId:
    Type: String
  PrdAccountId:
    Type: String

Resources:
  PipelineMonitorLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - codepipeline:ListPipelines
                - codepipeline:PutJobFailureResult
                - codepipeline:PutJobSuccessResult
              Resource: '*'
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Resource:
                - !Sub arn:aws:iam::${DevAccountId}:role/PipelineAutomationRole
                - !Sub arn:aws:iam::${CiAccountId}:role/PipelineAutomationRole
                - !Sub arn:aws:iam::${PrdAccountId}:role/PipelineAutomationRole
                - !Sub arn:aws:iam::${AWS::AccountId}:role/PipelineAutomationRole
      CodeUri: ./


Outputs:

  PipelineMonitorLambdaArn:
    Value: !GetAtt PipelineMonitorLambda.Arn
    Export:
      Name: !Sub ${AWS::StackName}-PipelineMonitorLambdaArn

  PipelineMonitorlambdaName:
    Value: !Ref PipelineMonitorLambda
    Export:
      Name: !Sub ${AWS::StackName}-PipelineMonitorLambdaName