name: mutation testing

on:
  push:
    branches: [ master ]
  pull_request:
      types: [opened, synchronize, reopened]

jobs:

  mutate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install
      run: yarn

    - name: Run unit tests
      run: yarn test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Run mutation tests
      run: yarn mutate
