name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
      types: [opened, synchronize, reopened]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: cfn-lint
      uses: scottbrenner/cfn-lint-action@master
      with:
        args: "codepipeline-waiter.yaml"

    - name: Install
      run: yarn

    - name: Run unit tests
      run: yarn test

    # Run sonar analysis
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
